<?php


/**
 * This class defines the structure of the 'admin' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 06/19/14 22:45:26
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AdminTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AdminTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('admin');
		$this->setPhpName('Admin');
		$this->setClassname('Admin');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ADM_ID', 'AdmId', 'INTEGER', true, 11, null);
		$this->addColumn('ADM_USER', 'AdmUser', 'VARCHAR', false, 20, null);
		$this->addColumn('ADM_PASS', 'AdmPass', 'VARCHAR', false, 32, null);
		$this->addColumn('ADM_EMAIL', 'AdmEmail', 'VARCHAR', false, 100, null);
		$this->addColumn('ADM_ESTADO', 'AdmEstado', 'SMALLINT', false, 6, 0);
		$this->addColumn('ADM_ELIMINADO', 'AdmEliminado', 'SMALLINT', false, 6, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // AdminTableMap
