<?php


/**
 * This class defines the structure of the 'diccionario' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 06/09/14 00:12:58
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class DiccionarioTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.DiccionarioTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('diccionario');
		$this->setPhpName('Diccionario');
		$this->setClassname('Diccionario');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('DIC_ID', 'DicId', 'INTEGER', true, 11, null);
		$this->addForeignKey('IDI_ID', 'IdiId', 'INTEGER', 'idioma', 'IDI_ID', true, 11, null);
		$this->addForeignKey('PAR_ID', 'ParId', 'INTEGER', 'parametro', 'PAR_ID', true, 11, null);
		$this->addColumn('DIC_TEXTO', 'DicTexto', 'LONGVARCHAR', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Parametro', 'Parametro', RelationMap::MANY_TO_ONE, array('par_id' => 'par_id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Idioma', 'Idioma', RelationMap::MANY_TO_ONE, array('idi_id' => 'idi_id', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // DiccionarioTableMap
