<?php


/**
 * This class defines the structure of the 'receta' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/04/14 03:51:42
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class RecetaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.RecetaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('receta');
		$this->setPhpName('Receta');
		$this->setClassname('Receta');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('REC_ID', 'RecId', 'INTEGER', true, 11, null);
		$this->addColumn('REC_NOMBRE_RECETA', 'RecNombreReceta', 'LONGVARCHAR', false, null, null);
		$this->addColumn('REC_INGREDIENTES', 'RecIngredientes', 'LONGVARCHAR', false, null, null);
		$this->addColumn('REC_INSTRUCCIONES', 'RecInstrucciones', 'LONGVARCHAR', false, null, null);
		$this->addColumn('REC_VINO', 'RecVino', 'VARCHAR', false, 200, null);
		$this->addColumn('REC_NOMBRE_BLOGGER', 'RecNombreBlogger', 'VARCHAR', false, 200, null);
		$this->addColumn('REC_EMAIL_BLOGGER', 'RecEmailBlogger', 'VARCHAR', false, 200, null);
		$this->addColumn('REC_URL_BLOGGER', 'RecUrlBlogger', 'VARCHAR', false, 200, null);
		$this->addColumn('REC_ESTADO', 'RecEstado', 'SMALLINT', false, 6, 0);
		$this->addColumn('REC_ELIMINADO', 'RecEliminado', 'SMALLINT', false, 6, 0);
		$this->addColumn('REC_IMAGEN', 'RecImagen', 'LONGVARCHAR', false, null, null);
		$this->addColumn('REC_PAIS', 'RecPais', 'SMALLINT', false, 6, 0);
		$this->addColumn('REC_SEMI', 'RecSemi', 'SMALLINT', true, 6, 0);
		$this->addColumn('REC_FINAL', 'RecFinal', 'SMALLINT', true, 6, 0);
		$this->addColumn('REC_GANADOR', 'RecGanador', 'SMALLINT', true, 6, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('UsuarioReceta', 'UsuarioReceta', RelationMap::ONE_TO_MANY, array('rec_id' => 'rec_id', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // RecetaTableMap
