<?php


/**
 * Skeleton subclass for representing a row from the 'seccion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 06/08/14 18:30:53
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Seccion extends BaseSeccion {
    
  public function __toString()
  {
    return $this->getSecNombre()." [".$this->getPagina()->getPagNombre()."]";
  }

} // Seccion
