<?php


/**
 * Skeleton subclass for representing a row from the 'usuario_receta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/04/14 03:51:43
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UsuarioReceta extends BaseUsuarioReceta {

} // UsuarioReceta
