<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/13 01:12:59

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=conosur',
  'username' => 'root',
  'password' => 'admin',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
