<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/06/05 23:09:04
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfmixer' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformfiltergenerator' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgenerateadmintask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoxmltask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sftesterpropel' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfwidgetformpropelchoice' => 'D:/Github/Cono-Sur/php-frontend/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',

  // project
  'baseform' => 'D:/Github/Cono-Sur/php-frontend/lib/form/BaseForm.class.php',

  // project_model
  'diccionario' => 'D:/Github/Cono-Sur/php-frontend/lib/model/Diccionario.php',
  'diccionariopeer' => 'D:/Github/Cono-Sur/php-frontend/lib/model/DiccionarioPeer.php',
  'idioma' => 'D:/Github/Cono-Sur/php-frontend/lib/model/Idioma.php',
  'idiomapeer' => 'D:/Github/Cono-Sur/php-frontend/lib/model/IdiomaPeer.php',
  'diccionariotablemap' => 'D:/Github/Cono-Sur/php-frontend/lib/model/map/DiccionarioTableMap.php',
  'idiomatablemap' => 'D:/Github/Cono-Sur/php-frontend/lib/model/map/IdiomaTableMap.php',
  'paginatablemap' => 'D:/Github/Cono-Sur/php-frontend/lib/model/map/PaginaTableMap.php',
  'parametrotablemap' => 'D:/Github/Cono-Sur/php-frontend/lib/model/map/ParametroTableMap.php',
  'basediccionario' => 'D:/Github/Cono-Sur/php-frontend/lib/model/om/BaseDiccionario.php',
  'basediccionariopeer' => 'D:/Github/Cono-Sur/php-frontend/lib/model/om/BaseDiccionarioPeer.php',
  'baseidioma' => 'D:/Github/Cono-Sur/php-frontend/lib/model/om/BaseIdioma.php',
  'baseidiomapeer' => 'D:/Github/Cono-Sur/php-frontend/lib/model/om/BaseIdiomaPeer.php',
  'basepagina' => 'D:/Github/Cono-Sur/php-frontend/lib/model/om/BasePagina.php',
  'basepaginapeer' => 'D:/Github/Cono-Sur/php-frontend/lib/model/om/BasePaginaPeer.php',
  'baseparametro' => 'D:/Github/Cono-Sur/php-frontend/lib/model/om/BaseParametro.php',
  'baseparametropeer' => 'D:/Github/Cono-Sur/php-frontend/lib/model/om/BaseParametroPeer.php',
  'pagina' => 'D:/Github/Cono-Sur/php-frontend/lib/model/Pagina.php',
  'paginapeer' => 'D:/Github/Cono-Sur/php-frontend/lib/model/PaginaPeer.php',
  'parametro' => 'D:/Github/Cono-Sur/php-frontend/lib/model/Parametro.php',
  'parametropeer' => 'D:/Github/Cono-Sur/php-frontend/lib/model/ParametroPeer.php',

  // application
  'myuser' => 'D:/Github/Cono-Sur/php-frontend/apps/backend/lib/myUser.class.php',

  // modules
);
