<?php

/**
 * Base class that represents a row from the 'receta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 06/02/15 21:20:20
 *
 * @package    lib.model.om
 */
abstract class BaseReceta extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RecetaPeer
	 */
	protected static $peer;

	/**
	 * The value for the rec_id field.
	 * @var        int
	 */
	protected $rec_id;

	/**
	 * The value for the rec_nombre_receta field.
	 * @var        string
	 */
	protected $rec_nombre_receta;

	/**
	 * The value for the rec_ingredientes field.
	 * @var        string
	 */
	protected $rec_ingredientes;

	/**
	 * The value for the rec_instrucciones field.
	 * @var        string
	 */
	protected $rec_instrucciones;

	/**
	 * The value for the rec_vino field.
	 * @var        string
	 */
	protected $rec_vino;

	/**
	 * The value for the rec_nombre_blogger field.
	 * @var        string
	 */
	protected $rec_nombre_blogger;

	/**
	 * The value for the rec_email_blogger field.
	 * @var        string
	 */
	protected $rec_email_blogger;

	/**
	 * The value for the rec_url_blogger field.
	 * @var        string
	 */
	protected $rec_url_blogger;

	/**
	 * The value for the rec_urlname_blogger field.
	 * @var        string
	 */
	protected $rec_urlname_blogger;

	/**
	 * The value for the rec_estado field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rec_estado;

	/**
	 * The value for the rec_eliminado field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rec_eliminado;

	/**
	 * The value for the rec_imagen field.
	 * @var        string
	 */
	protected $rec_imagen;

	/**
	 * The value for the rec_pais field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rec_pais;

	/**
	 * The value for the rec_semi field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rec_semi;

	/**
	 * The value for the rec_final field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rec_final;

	/**
	 * The value for the rec_ganador field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rec_ganador;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        array UsuarioReceta[] Collection to store aggregation of UsuarioReceta objects.
	 */
	protected $collUsuarioRecetas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUsuarioRecetas.
	 */
	private $lastUsuarioRecetaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'RecetaPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->rec_estado = 0;
		$this->rec_eliminado = 0;
		$this->rec_pais = 0;
		$this->rec_semi = 0;
		$this->rec_final = 0;
		$this->rec_ganador = 0;
	}

	/**
	 * Initializes internal state of BaseReceta object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [rec_id] column value.
	 * 
	 * @return     int
	 */
	public function getRecId()
	{
		return $this->rec_id;
	}

	/**
	 * Get the [rec_nombre_receta] column value.
	 * 
	 * @return     string
	 */
	public function getRecNombreReceta()
	{
		return $this->rec_nombre_receta;
	}

	/**
	 * Get the [rec_ingredientes] column value.
	 * 
	 * @return     string
	 */
	public function getRecIngredientes()
	{
		return $this->rec_ingredientes;
	}

	/**
	 * Get the [rec_instrucciones] column value.
	 * 
	 * @return     string
	 */
	public function getRecInstrucciones()
	{
		return $this->rec_instrucciones;
	}

	/**
	 * Get the [rec_vino] column value.
	 * 
	 * @return     string
	 */
	public function getRecVino()
	{
		return $this->rec_vino;
	}

	/**
	 * Get the [rec_nombre_blogger] column value.
	 * 
	 * @return     string
	 */
	public function getRecNombreBlogger()
	{
		return $this->rec_nombre_blogger;
	}

	/**
	 * Get the [rec_email_blogger] column value.
	 * 
	 * @return     string
	 */
	public function getRecEmailBlogger()
	{
		return $this->rec_email_blogger;
	}

	/**
	 * Get the [rec_url_blogger] column value.
	 * 
	 * @return     string
	 */
	public function getRecUrlBlogger()
	{
		return $this->rec_url_blogger;
	}

	/**
	 * Get the [rec_urlname_blogger] column value.
	 * 
	 * @return     string
	 */
	public function getRecUrlnameBlogger()
	{
		return $this->rec_urlname_blogger;
	}

	/**
	 * Get the [rec_estado] column value.
	 * 
	 * @return     int
	 */
	public function getRecEstado()
	{
		return $this->rec_estado;
	}

	/**
	 * Get the [rec_eliminado] column value.
	 * 
	 * @return     int
	 */
	public function getRecEliminado()
	{
		return $this->rec_eliminado;
	}

	/**
	 * Get the [rec_imagen] column value.
	 * 
	 * @return     string
	 */
	public function getRecImagen()
	{
		return $this->rec_imagen;
	}

	/**
	 * Get the [rec_pais] column value.
	 * 
	 * @return     int
	 */
	public function getRecPais()
	{
		return $this->rec_pais;
	}

	/**
	 * Get the [rec_semi] column value.
	 * 
	 * @return     int
	 */
	public function getRecSemi()
	{
		return $this->rec_semi;
	}

	/**
	 * Get the [rec_final] column value.
	 * 
	 * @return     int
	 */
	public function getRecFinal()
	{
		return $this->rec_final;
	}

	/**
	 * Get the [rec_ganador] column value.
	 * 
	 * @return     int
	 */
	public function getRecGanador()
	{
		return $this->rec_ganador;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [rec_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rec_id !== $v) {
			$this->rec_id = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_ID;
		}

		return $this;
	} // setRecId()

	/**
	 * Set the value of [rec_nombre_receta] column.
	 * 
	 * @param      string $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecNombreReceta($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->rec_nombre_receta !== $v) {
			$this->rec_nombre_receta = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_NOMBRE_RECETA;
		}

		return $this;
	} // setRecNombreReceta()

	/**
	 * Set the value of [rec_ingredientes] column.
	 * 
	 * @param      string $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecIngredientes($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->rec_ingredientes !== $v) {
			$this->rec_ingredientes = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_INGREDIENTES;
		}

		return $this;
	} // setRecIngredientes()

	/**
	 * Set the value of [rec_instrucciones] column.
	 * 
	 * @param      string $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecInstrucciones($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->rec_instrucciones !== $v) {
			$this->rec_instrucciones = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_INSTRUCCIONES;
		}

		return $this;
	} // setRecInstrucciones()

	/**
	 * Set the value of [rec_vino] column.
	 * 
	 * @param      string $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecVino($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->rec_vino !== $v) {
			$this->rec_vino = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_VINO;
		}

		return $this;
	} // setRecVino()

	/**
	 * Set the value of [rec_nombre_blogger] column.
	 * 
	 * @param      string $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecNombreBlogger($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->rec_nombre_blogger !== $v) {
			$this->rec_nombre_blogger = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_NOMBRE_BLOGGER;
		}

		return $this;
	} // setRecNombreBlogger()

	/**
	 * Set the value of [rec_email_blogger] column.
	 * 
	 * @param      string $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecEmailBlogger($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->rec_email_blogger !== $v) {
			$this->rec_email_blogger = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_EMAIL_BLOGGER;
		}

		return $this;
	} // setRecEmailBlogger()

	/**
	 * Set the value of [rec_url_blogger] column.
	 * 
	 * @param      string $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecUrlBlogger($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->rec_url_blogger !== $v) {
			$this->rec_url_blogger = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_URL_BLOGGER;
		}

		return $this;
	} // setRecUrlBlogger()

	/**
	 * Set the value of [rec_urlname_blogger] column.
	 * 
	 * @param      string $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecUrlnameBlogger($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->rec_urlname_blogger !== $v) {
			$this->rec_urlname_blogger = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_URLNAME_BLOGGER;
		}

		return $this;
	} // setRecUrlnameBlogger()

	/**
	 * Set the value of [rec_estado] column.
	 * 
	 * @param      int $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecEstado($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rec_estado !== $v || $this->isNew()) {
			$this->rec_estado = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_ESTADO;
		}

		return $this;
	} // setRecEstado()

	/**
	 * Set the value of [rec_eliminado] column.
	 * 
	 * @param      int $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecEliminado($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rec_eliminado !== $v || $this->isNew()) {
			$this->rec_eliminado = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_ELIMINADO;
		}

		return $this;
	} // setRecEliminado()

	/**
	 * Set the value of [rec_imagen] column.
	 * 
	 * @param      string $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecImagen($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->rec_imagen !== $v) {
			$this->rec_imagen = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_IMAGEN;
		}

		return $this;
	} // setRecImagen()

	/**
	 * Set the value of [rec_pais] column.
	 * 
	 * @param      int $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecPais($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rec_pais !== $v || $this->isNew()) {
			$this->rec_pais = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_PAIS;
		}

		return $this;
	} // setRecPais()

	/**
	 * Set the value of [rec_semi] column.
	 * 
	 * @param      int $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecSemi($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rec_semi !== $v || $this->isNew()) {
			$this->rec_semi = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_SEMI;
		}

		return $this;
	} // setRecSemi()

	/**
	 * Set the value of [rec_final] column.
	 * 
	 * @param      int $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecFinal($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rec_final !== $v || $this->isNew()) {
			$this->rec_final = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_FINAL;
		}

		return $this;
	} // setRecFinal()

	/**
	 * Set the value of [rec_ganador] column.
	 * 
	 * @param      int $v new value
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setRecGanador($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rec_ganador !== $v || $this->isNew()) {
			$this->rec_ganador = $v;
			$this->modifiedColumns[] = RecetaPeer::REC_GANADOR;
		}

		return $this;
	} // setRecGanador()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = RecetaPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Receta The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = RecetaPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->rec_estado !== 0) {
				return false;
			}

			if ($this->rec_eliminado !== 0) {
				return false;
			}

			if ($this->rec_pais !== 0) {
				return false;
			}

			if ($this->rec_semi !== 0) {
				return false;
			}

			if ($this->rec_final !== 0) {
				return false;
			}

			if ($this->rec_ganador !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->rec_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->rec_nombre_receta = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->rec_ingredientes = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->rec_instrucciones = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->rec_vino = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->rec_nombre_blogger = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->rec_email_blogger = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->rec_url_blogger = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->rec_urlname_blogger = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->rec_estado = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->rec_eliminado = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->rec_imagen = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->rec_pais = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->rec_semi = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->rec_final = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->rec_ganador = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
			$this->created_at = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->updated_at = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 18; // 18 = RecetaPeer::NUM_COLUMNS - RecetaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Receta object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RecetaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RecetaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collUsuarioRecetas = null;
			$this->lastUsuarioRecetaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RecetaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseReceta:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				RecetaPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseReceta:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RecetaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseReceta:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(RecetaPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(RecetaPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseReceta:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				RecetaPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RecetaPeer::REC_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RecetaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setRecId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RecetaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collUsuarioRecetas !== null) {
				foreach ($this->collUsuarioRecetas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = RecetaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collUsuarioRecetas !== null) {
					foreach ($this->collUsuarioRecetas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RecetaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getRecId();
				break;
			case 1:
				return $this->getRecNombreReceta();
				break;
			case 2:
				return $this->getRecIngredientes();
				break;
			case 3:
				return $this->getRecInstrucciones();
				break;
			case 4:
				return $this->getRecVino();
				break;
			case 5:
				return $this->getRecNombreBlogger();
				break;
			case 6:
				return $this->getRecEmailBlogger();
				break;
			case 7:
				return $this->getRecUrlBlogger();
				break;
			case 8:
				return $this->getRecUrlnameBlogger();
				break;
			case 9:
				return $this->getRecEstado();
				break;
			case 10:
				return $this->getRecEliminado();
				break;
			case 11:
				return $this->getRecImagen();
				break;
			case 12:
				return $this->getRecPais();
				break;
			case 13:
				return $this->getRecSemi();
				break;
			case 14:
				return $this->getRecFinal();
				break;
			case 15:
				return $this->getRecGanador();
				break;
			case 16:
				return $this->getCreatedAt();
				break;
			case 17:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RecetaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getRecId(),
			$keys[1] => $this->getRecNombreReceta(),
			$keys[2] => $this->getRecIngredientes(),
			$keys[3] => $this->getRecInstrucciones(),
			$keys[4] => $this->getRecVino(),
			$keys[5] => $this->getRecNombreBlogger(),
			$keys[6] => $this->getRecEmailBlogger(),
			$keys[7] => $this->getRecUrlBlogger(),
			$keys[8] => $this->getRecUrlnameBlogger(),
			$keys[9] => $this->getRecEstado(),
			$keys[10] => $this->getRecEliminado(),
			$keys[11] => $this->getRecImagen(),
			$keys[12] => $this->getRecPais(),
			$keys[13] => $this->getRecSemi(),
			$keys[14] => $this->getRecFinal(),
			$keys[15] => $this->getRecGanador(),
			$keys[16] => $this->getCreatedAt(),
			$keys[17] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RecetaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setRecId($value);
				break;
			case 1:
				$this->setRecNombreReceta($value);
				break;
			case 2:
				$this->setRecIngredientes($value);
				break;
			case 3:
				$this->setRecInstrucciones($value);
				break;
			case 4:
				$this->setRecVino($value);
				break;
			case 5:
				$this->setRecNombreBlogger($value);
				break;
			case 6:
				$this->setRecEmailBlogger($value);
				break;
			case 7:
				$this->setRecUrlBlogger($value);
				break;
			case 8:
				$this->setRecUrlnameBlogger($value);
				break;
			case 9:
				$this->setRecEstado($value);
				break;
			case 10:
				$this->setRecEliminado($value);
				break;
			case 11:
				$this->setRecImagen($value);
				break;
			case 12:
				$this->setRecPais($value);
				break;
			case 13:
				$this->setRecSemi($value);
				break;
			case 14:
				$this->setRecFinal($value);
				break;
			case 15:
				$this->setRecGanador($value);
				break;
			case 16:
				$this->setCreatedAt($value);
				break;
			case 17:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RecetaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setRecId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setRecNombreReceta($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setRecIngredientes($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setRecInstrucciones($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setRecVino($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setRecNombreBlogger($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setRecEmailBlogger($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setRecUrlBlogger($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setRecUrlnameBlogger($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setRecEstado($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setRecEliminado($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setRecImagen($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setRecPais($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setRecSemi($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setRecFinal($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setRecGanador($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setCreatedAt($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setUpdatedAt($arr[$keys[17]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RecetaPeer::DATABASE_NAME);

		if ($this->isColumnModified(RecetaPeer::REC_ID)) $criteria->add(RecetaPeer::REC_ID, $this->rec_id);
		if ($this->isColumnModified(RecetaPeer::REC_NOMBRE_RECETA)) $criteria->add(RecetaPeer::REC_NOMBRE_RECETA, $this->rec_nombre_receta);
		if ($this->isColumnModified(RecetaPeer::REC_INGREDIENTES)) $criteria->add(RecetaPeer::REC_INGREDIENTES, $this->rec_ingredientes);
		if ($this->isColumnModified(RecetaPeer::REC_INSTRUCCIONES)) $criteria->add(RecetaPeer::REC_INSTRUCCIONES, $this->rec_instrucciones);
		if ($this->isColumnModified(RecetaPeer::REC_VINO)) $criteria->add(RecetaPeer::REC_VINO, $this->rec_vino);
		if ($this->isColumnModified(RecetaPeer::REC_NOMBRE_BLOGGER)) $criteria->add(RecetaPeer::REC_NOMBRE_BLOGGER, $this->rec_nombre_blogger);
		if ($this->isColumnModified(RecetaPeer::REC_EMAIL_BLOGGER)) $criteria->add(RecetaPeer::REC_EMAIL_BLOGGER, $this->rec_email_blogger);
		if ($this->isColumnModified(RecetaPeer::REC_URL_BLOGGER)) $criteria->add(RecetaPeer::REC_URL_BLOGGER, $this->rec_url_blogger);
		if ($this->isColumnModified(RecetaPeer::REC_URLNAME_BLOGGER)) $criteria->add(RecetaPeer::REC_URLNAME_BLOGGER, $this->rec_urlname_blogger);
		if ($this->isColumnModified(RecetaPeer::REC_ESTADO)) $criteria->add(RecetaPeer::REC_ESTADO, $this->rec_estado);
		if ($this->isColumnModified(RecetaPeer::REC_ELIMINADO)) $criteria->add(RecetaPeer::REC_ELIMINADO, $this->rec_eliminado);
		if ($this->isColumnModified(RecetaPeer::REC_IMAGEN)) $criteria->add(RecetaPeer::REC_IMAGEN, $this->rec_imagen);
		if ($this->isColumnModified(RecetaPeer::REC_PAIS)) $criteria->add(RecetaPeer::REC_PAIS, $this->rec_pais);
		if ($this->isColumnModified(RecetaPeer::REC_SEMI)) $criteria->add(RecetaPeer::REC_SEMI, $this->rec_semi);
		if ($this->isColumnModified(RecetaPeer::REC_FINAL)) $criteria->add(RecetaPeer::REC_FINAL, $this->rec_final);
		if ($this->isColumnModified(RecetaPeer::REC_GANADOR)) $criteria->add(RecetaPeer::REC_GANADOR, $this->rec_ganador);
		if ($this->isColumnModified(RecetaPeer::CREATED_AT)) $criteria->add(RecetaPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(RecetaPeer::UPDATED_AT)) $criteria->add(RecetaPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RecetaPeer::DATABASE_NAME);

		$criteria->add(RecetaPeer::REC_ID, $this->rec_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getRecId();
	}

	/**
	 * Generic method to set the primary key (rec_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setRecId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Receta (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setRecNombreReceta($this->rec_nombre_receta);

		$copyObj->setRecIngredientes($this->rec_ingredientes);

		$copyObj->setRecInstrucciones($this->rec_instrucciones);

		$copyObj->setRecVino($this->rec_vino);

		$copyObj->setRecNombreBlogger($this->rec_nombre_blogger);

		$copyObj->setRecEmailBlogger($this->rec_email_blogger);

		$copyObj->setRecUrlBlogger($this->rec_url_blogger);

		$copyObj->setRecUrlnameBlogger($this->rec_urlname_blogger);

		$copyObj->setRecEstado($this->rec_estado);

		$copyObj->setRecEliminado($this->rec_eliminado);

		$copyObj->setRecImagen($this->rec_imagen);

		$copyObj->setRecPais($this->rec_pais);

		$copyObj->setRecSemi($this->rec_semi);

		$copyObj->setRecFinal($this->rec_final);

		$copyObj->setRecGanador($this->rec_ganador);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getUsuarioRecetas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUsuarioReceta($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setRecId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Receta Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RecetaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RecetaPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collUsuarioRecetas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUsuarioRecetas()
	 */
	public function clearUsuarioRecetas()
	{
		$this->collUsuarioRecetas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUsuarioRecetas collection (array).
	 *
	 * By default this just sets the collUsuarioRecetas collection to an empty array (like clearcollUsuarioRecetas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUsuarioRecetas()
	{
		$this->collUsuarioRecetas = array();
	}

	/**
	 * Gets an array of UsuarioReceta objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Receta has previously been saved, it will retrieve
	 * related UsuarioRecetas from storage. If this Receta is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UsuarioReceta[]
	 * @throws     PropelException
	 */
	public function getUsuarioRecetas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RecetaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsuarioRecetas === null) {
			if ($this->isNew()) {
			   $this->collUsuarioRecetas = array();
			} else {

				$criteria->add(UsuarioRecetaPeer::REC_ID, $this->rec_id);

				UsuarioRecetaPeer::addSelectColumns($criteria);
				$this->collUsuarioRecetas = UsuarioRecetaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UsuarioRecetaPeer::REC_ID, $this->rec_id);

				UsuarioRecetaPeer::addSelectColumns($criteria);
				if (!isset($this->lastUsuarioRecetaCriteria) || !$this->lastUsuarioRecetaCriteria->equals($criteria)) {
					$this->collUsuarioRecetas = UsuarioRecetaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUsuarioRecetaCriteria = $criteria;
		return $this->collUsuarioRecetas;
	}

	/**
	 * Returns the number of related UsuarioReceta objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UsuarioReceta objects.
	 * @throws     PropelException
	 */
	public function countUsuarioRecetas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RecetaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUsuarioRecetas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UsuarioRecetaPeer::REC_ID, $this->rec_id);

				$count = UsuarioRecetaPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UsuarioRecetaPeer::REC_ID, $this->rec_id);

				if (!isset($this->lastUsuarioRecetaCriteria) || !$this->lastUsuarioRecetaCriteria->equals($criteria)) {
					$count = UsuarioRecetaPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collUsuarioRecetas);
				}
			} else {
				$count = count($this->collUsuarioRecetas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UsuarioReceta object to this object
	 * through the UsuarioReceta foreign key attribute.
	 *
	 * @param      UsuarioReceta $l UsuarioReceta
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUsuarioReceta(UsuarioReceta $l)
	{
		if ($this->collUsuarioRecetas === null) {
			$this->initUsuarioRecetas();
		}
		if (!in_array($l, $this->collUsuarioRecetas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUsuarioRecetas, $l);
			$l->setReceta($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Receta is new, it will return
	 * an empty collection; or if this Receta has previously
	 * been saved, it will retrieve related UsuarioRecetas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Receta.
	 */
	public function getUsuarioRecetasJoinUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RecetaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsuarioRecetas === null) {
			if ($this->isNew()) {
				$this->collUsuarioRecetas = array();
			} else {

				$criteria->add(UsuarioRecetaPeer::REC_ID, $this->rec_id);

				$this->collUsuarioRecetas = UsuarioRecetaPeer::doSelectJoinUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UsuarioRecetaPeer::REC_ID, $this->rec_id);

			if (!isset($this->lastUsuarioRecetaCriteria) || !$this->lastUsuarioRecetaCriteria->equals($criteria)) {
				$this->collUsuarioRecetas = UsuarioRecetaPeer::doSelectJoinUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastUsuarioRecetaCriteria = $criteria;

		return $this->collUsuarioRecetas;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collUsuarioRecetas) {
				foreach ((array) $this->collUsuarioRecetas as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collUsuarioRecetas = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseReceta:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseReceta::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseReceta
